version: '3.8'

services:
  srs:
    image: ossrs/srs:5
    ports:
      - "1935:1935"  # RTMP
      - "1985:1985"  # HTTP API
      - "8082:8080"  # HTTP FLV
      - "8002:8000/udp"  # UDP
      - "10080:10080/udp"  # UDP
    restart: unless-stopped
    networks:
      - visionhog_network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - visionhog_network

  visionhog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - ./video_clips:/app/video_clips
      - ./processed_clips:/app/processed_clips
    environment:
      - USE_MINIO=true
      - S3_BUCKET=posthog-vision
      - S3_PREFIX=teams/2
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=false
      - STREAM_URL=http://srs:8080/live/show.flv
      - POSTHOG_ENV_KEY=${POSTHOG_ENV_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    depends_on:
      - srs
      - minio
    restart: unless-stopped
    networks:
      - visionhog_network

networks:
  visionhog_network:
    driver: bridge

volumes:
  minio_data:
